version: '3.6'
services:
  api:
    build: api
    restart: always
    command: >
      bash -c "npm install
      && npm run dev"
    ports:
      - 8000:8000
    volumes:
      - tmp:/usr/src/app/tmp
      - ./routes:/usr/src/app/
    networks:
      - db-network
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/usr/src/app/mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  tmp:
  api:
  mongo:
